### ISSUE TITLE
This library doesn't appear on https://www.arduino.cc/en/Reference/Libraries list

### ISSUE THREAD

**Issue by q2dg** [arduino-libraries/WiFiNINA#1]

**Comment by sandeepmistry** [comment]
@q2dg it's further down, in the `MKR WiFi 1010, MKR VIDOR 4000 and Arduino UNO WiFi Rev.2` section:

<img width="908" alt="screen shot 2018-07-23 at 1 50 23 pm" src="https://user-images.githubusercontent.com/1163840/43093893-6aed6e78-8e7f-11e8-9250-20c1059ae2a6.png">

cc/ @simonepda

**Comment by q2dg** [comment]
Oooh, so sorry!!
