### ISSUE TITLE
Deep sleep

### ISSUE THREAD

**Issue by eduardcabanas** [arduino-libraries/WiFiNINA#11]
Hi,

We are developing a station that reads some sensors and after reading send the info to the server. After this process goes to sleep.

We are using MKRFOX1200 and low-power library and It works, but when I'm using with mkr wifi1010 the module still consumes energy in a voracious way.

IS it possible to cut the energy to hall mkrwifi1010? or deep sleep the wifi module?

thank's for your help

Eduard

**Comment by sandeepmistry** [comment]
Closing for now due to lack of response.
