### ISSUE TITLE
mDNS

### ISSUE THREAD

**Issue by fmatray** [arduino-libraries/WiFiNINA#119]
Hello,
Is it possible to port WiFiMDNSResponder from the library  WIFI101 into WifiNINA ?

**Comment by cansik** [comment]
If it is just based on the `WiFiUDP`, it should not be a problem. For me the [ArduinoMDNS](https://github.com/arduino-libraries/ArduinoMDNS) worked out of the box with WiFiNINA.

**Comment by fmatray** [comment]
Thanks a lot
