### ISSUE TITLE
WiFi.ping(hostName) returns cryptic values

### ISSUE THREAD

**Issue by systembolaget** [arduino-libraries/WiFiNINA#122]
When I use **WiFi.ping(hostName)** and have no Internet connection, I get a return value of **-3**, and with Internet connection, I get a value of **10**. What do these values mean?

Reason: testing for **WL_CONNECTED** being ok with a return value of **3** only indicates a successful connection to the router, but not necessarily to the Internet, when, for example, a restarted router spawns the WLAN very quickly, but can take up to 2 minutes to also establish the DSL connection to the ISP. Therefore, I want to check with WiFi.ping() if I can reach some always-on host, like Google or other, thus indicating that not only the WLAN is up again after a power outage, but also the Internet connection is up.

The return values of -3 (WLAN reconnected but Internet not yet reconnected) and 10 (WLAN and Internet both reconnected) are very cryptic, and there may be other return values, too, so some kind of overview would be very helpful.

Much appreciated!

**Comment by jandrassy** [comment]
```
if (pingResult == WL_PING_DEST_UNREACHABLE) {
  Serial.println("Host unreachable");
}
```

**Comment by systembolaget** [comment]
As I now know what the formerly cryptic numbers mean, I can now test for all three cases:

1.	The WLAN network is up and the Internet can be reached
2.	The WLAN network is up and the Internet cannot be reached
3.	The WLAN network is down (and consequently the Internet cannot be reached)

This will be a good use case for a state machine.

**Comment by jandrassy** [comment]
> 
> 
> As I now know what the formerly cryptic numbers mean, I can now test for all three cases:
> 
>     1. The WLAN network is up and the Internet can be reached
> 
>     2. The WLAN network is up and the Internet cannot be reached
> 
>     3. The WLAN network is down (and consequently the Internet cannot be reached)
> 
> 
> This will be a good use case for a state machine.

how will the error code numbers help with it? you should not use the numbers but the constants names
