### ISSUE TITLE
Problem with firmware version

### ISSUE THREAD

**Issue by bertox94** [arduino-libraries/WiFiNINA#132]
Hi, on MKR1010 I run the sketch CheckFirmwareVersion and says: 

_Firmware version installed: 1.3.0
Latest firmware version available : 1.4.1

Check result: NOT PASSED_

But when I try to update it, the latest version available is the 1.3.0 which I already have.

**Comment by montoyamoraga** [comment]
i am commenting here because i have the exact same issue

**Comment by khoih-prog** [comment]
You can try to follow the instructions here

[**HOWTO Update WiFiNINA Firmware**](https://github.com/khoih-prog/WiFiNINA_Generic#howto-update-wifinina-firmware-latest-version-is-v141-as-of-august-2020)
