### ISSUE TITLE
Warning during compilation

### ISSUE THREAD

**Issue by fmatray** [arduino-libraries/WiFiNINA#136]
There is a Warning in spi_drv.cpp in last version 

.pio/libdeps/mkrwifi1010/WiFiNINA/src/utility/spi_drv.cpp: In static member function 'static void SpiDrv::sendParamNoLen(uint8_t*, size_t, uint8_t)':
.pio/libdeps/mkrwifi1010/WiFiNINA/src/utility/spi_drv.cpp:459:16: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
     for (i=0; i<param_len; ++i)
               ~^~~~~~~~~~

Easy fix :
change 
int i = 0;
to
size_t i = 0;

**Comment by facchinm** [comment]
Hi @fmatray ,
thanks for noticing! Would you create a PR so we can keep attribution? Thanks!

**Comment by fmatray** [comment]
Done.
Sorry for the delay.
