### ISSUE TITLE
Backslash and double quote characters in passphrase

### ISSUE THREAD

**Issue by TechnicalLee** [arduino-libraries/WiFiNINA#145]
If the WiFi password happens to contain a backslash \ or a double quote " character, the device will not connect. These two characters are part of the ASCII printable characters set (32-126) which are the valid characters in the WPA/WPA2 specs, therefore they should work to be WPA compliant. Perhaps the code could parse these more intelligently.

I've found the following workarounds with escape characters:

1. If the passphrase contains a backslash `abcd\efg` then enter `abcd\\efg`
2. If the passphrase contains a double quote `abcd"efg` then enter `abcd\"efg`

I've tried all other valid characters (including space), they all work except those two. I apologize if this issue seems obvious, but it is very confusing to beginners.

**Comment by per1234** [comment]
Thanks for your suggestion @TechnicalLee. The need to escape these characters in strings is universal to C++/Arduino language in general. Your proposal to make the library code handle improperly escaped strings simply isn't feasible (and the code won't even compile in the case of an unescaped double quote).

The lack of documentation of this in the Arduino Language Reference is absolutely a deficiency which should be corrected. You are welcome to submit a pull request to add that information. The source content is hosted here:

https://github.com/arduino/reference-en/blob/master/Language/Variables/Data%20Types/string.adoc
