### ISSUE TITLE
1.8.7 issue comparing firmware

### ISSUE THREAD

**Issue by GeoffreyHayward** [arduino-libraries/WiFiNINA#164]
Hi,

My Arduino IDE upgraded WiFiNina to 1.8.7. When my sketch hits:

```
if (WiFi.firmwareVersion() < WIFI_FIRMWARE_LATEST_VERSION) {
      Serial.println(WiFi.firmwareVersion());
      Serial.println(WIFI_FIRMWARE_LATEST_VERSION);
      Serial.println("Please upgrade the firmware");
}
```

The serial prints:

```
1.4.3
1.4.3
Please upgrade the firmware
```

When I removed it:

```
/* if (WiFi.firmwareVersion() < WIFI_FIRMWARE_LATEST_VERSION) {
      Serial.println(WiFi.firmwareVersion());
      Serial.println(WIFI_FIRMWARE_LATEST_VERSION);
      Serial.println("Please upgrade the firmware");
} */
```

My sketch seems to work. 

I also tried `WiFi.firmwareVersion() != WIFI_FIRMWARE_LATEST_VERSION` but also ended up seing "Please upgrade the firmware".

It's very strange.

**Comment by pennam** [comment]
`WiFi.firmwareVersion()` returns a `char *` and `WIFI_FIRMWARE_LATEST_VERSION` is also a `const char array` they are not `String` objects. 
You can compare them in this way:

```
if (String(WiFi.firmwareVersion()) < String(WIFI_FIRMWARE_LATEST_VERSION)) {
...
}
```
or using `strcmp()`
