### ISSUE TITLE
failure to connect to AP with WAP 

### ISSUE THREAD

**Issue by grezco** [arduino-libraries/WiFiNINA#20]
Hello,

I have a problem with 2 MKR WIFI 1010 board to connected on a extended wifi router (TPLink RE650).
The Wifi.status result is alway 1 (WL_NO_SSID_AVAIL) but the router indicate to me that the board is connected and I can also ping it.
Any other device connects to it and so do 2 MKR1000 boards on the latest firmware 19.5.4.

Any help is greatly appreciated.
thanks

**Comment by grezco** [comment]
Hi @sandeepmistry, thanks you  !
It works with the changes in pull request #17

**Comment by sandeepmistry** [comment]
@grezco thank you for your feedback! I've just merged #17, it will be part of the next WiFiNINA library release.
