### ISSUE TITLE
Incorrect header comments in example sketches

### ISSUE THREAD

**Issue by sandeepmistry** [arduino-libraries/WiFiNINA#22]
Reported by @8bitkick, several of the examples have references to the WiFi Shield or MKR1000 in the comments. These need to be updated.

- https://github.com/arduino-libraries/WiFiNINA/blob/master/examples/ScanNetworks/ScanNetworks.ino
- https://github.com/arduino-libraries/WiFiNINA/blob/master/examples/ScanNetworksAdvanced/ScanNetworksAdvanced.ino
- https://github.com/arduino-libraries/WiFiNINA/blob/master/examples/SimpleWebServerWiFi/SimpleWebServerWiFi.ino
- https://github.com/arduino-libraries/WiFiNINA/blob/master/examples/WiFiChatServer/WiFiChatServer.ino
- https://github.com/arduino-libraries/WiFiNINA/blob/master/examples/WiFiPing/WiFiPing.ino
- https://github.com/arduino-libraries/WiFiNINA/blob/master/examples/WiFiWebClient/WiFiWebClient.ino

**Comment by Rocketct** [comment]
Closing via https://github.com/arduino-libraries/WiFiNINA/pull/35
