### ISSUE TITLE
Please add WIFI_ALL_CHANNEL_SCAN for multiple AP environment

### ISSUE THREAD

**Issue by wasteofpaint** [arduino-libraries/WiFiNINA#268]
Using Nano33iot boards with NINA FW 1.5.0 in an environment with multiple APs broadcasting the same SSID. The Arduinos do not connect to the AP with the strongest signal. If seems that this is due to the wifi module being configured to use WIFI_FAST_SCAN instead of WIFI_ALL_CHANNEL_SCAN. This was changed in NINA FW version 1.2.2. Can you revert this change, or make the option user selectable for those of us that are trying to use these boards in a multi AP environment? 

Thanks!

**Comment by per1234** [comment]
Hi @wasteofpaint. Thanks for taking the time to submit an issue.

I see we are already tracking the request for being able to enable the `WIFI_ALL_CHANNEL_SCAN` mode at https://github.com/arduino-libraries/WiFiNINA/issues/200.

It is best to have only a single issue per subject, so I'll go ahead and close this in favor of the other.

You can monitor that issue for updates related to this report.
