### ISSUE TITLE
printMacAddress()

### ISSUE THREAD

**Issue by durasno** [arduino-libraries/WiFiNINA#32]
The printMacAddress() function in the [ScanNetworks](https://github.com/arduino-libraries/WiFiNINA/blob/master/examples/ScanNetworks/ScanNetworks.ino) example returns an 11 character MAC address of the form:

AA:BB:CC:11:2:33

instead of:

AA:BB:CC:11:22:33

Software/hardware: OS X Yosemite, Arduino IDE 1.8.5, Arduino MKR WiFi 1010

**Comment by Rocketct** [comment]
Closed via https://github.com/arduino-libraries/WiFiNINA/pull/38#pullrequestreview-168822117
