### ISSUE TITLE
MKR1010 consumption

### ISSUE THREAD

**Issue by grezco** [arduino-libraries/WiFiNINA#40]
Hello,

I'm not sure Wifi.end() really turns off the WiFi module.
I have the same consumption with, or without this instruction before a LowPower.sleep().
I'm close to 50mA, while without starting the Wifi, I get 17mA in standby mode.

**Comment by sandeepmistry** [comment]
Hi @grezco,

Thanks for bringing this to our attention. I've opened pull request #42 to resolve this. Would you be able to try the changes and provide you feedback.

The reset pin of the WiFi module was being switched to input mode when it should have been left as an output (HIGH).

**Comment by grezco** [comment]
wonderful!
I will be able to reduce my consumption by a ratio of 3.

Thanks
