### ISSUE TITLE
does not connect to wifi

### ISSUE THREAD

**Issue by Nungaray9** [arduino-libraries/WiFiNINA#51]
good afternoon, there is a problem connecting to the internet, board MKR WIFI 1010, Library Wifinina 1.3.0
![image](https://user-images.githubusercontent.com/48767695/54949603-135fff80-4f05-11e9-9e94-ac5f8e03c404.png)

**Comment by sabas1080** [comment]
I have the same error in MKR1010

**Comment by Rocketct** [comment]
Hi @Nungaray9 which version of the firmware are you using?

**Comment by Rocketct** [comment]
closed due to lack of feedback, @Nungaray9 if you need reopen the issue please!
