### ISSUE TITLE
Add timeout for connect

### ISSUE THREAD

**Issue by tatulea** [arduino-libraries/WiFiNINA#7]
Hi,

I think that you should add a timeout parameter for connect methods. I did it locally for me as I need it.

Thanks

**Comment by sandeepmistry** [comment]
There's a similar discussion on this in the WiFi101 library: https://github.com/arduino-libraries/WiFi101/pull/172

**Comment by sandeepmistry** [comment]
Resolved via https://github.com/arduino-libraries/WiFiNINA/pull/46 by @Rocketct.
