### ISSUE TITLE
WiFiClient::available() function is taking long time in WiFiNINA library compared to WiFi101

### ISSUE THREAD

**Issue by akumar36** [arduino-libraries/WiFiNINA#80]
WiFiClient::available() function is taking 300uS to give the status whereas it took only 7uS with WiFi101 library. Seeing similar behaviour with WiFiClient::connected() function which is taking 700uS.

I've tested with MKR1010 and MKR1000 boards.

**Comment by sandeepmistry** [comment]
Pull request #84 will slightly help with the performance of this. We'd welcome any feedback you had on this change.
