### ISSUE TITLE
Its compatible with Arduinos 33 ble ?

### ISSUE THREAD

**Issue by enrutador** [arduino-libraries/WiFiNINA#81]
Great job! Is this library compatible with the new family of arduinos 33 Ble?

Thank you

**Comment by per1234** [comment]
The WiFiNINA library is for the Arduino boards that have a u-blox NINA-W102 ESP32 WiFi module attached. The Nano 33 BLE boards don't have a NINA-W102 module so you can't use them with the WiFiNINA library. These boards do not have WiFi functionality, only BLE provided by the NINA-B306 module.

So the only way it could possibly make sense to even try using this library with a Nano 33 BLE would be if you had a separate NINA-W102 attached to your Nano 33 BLE.

If you want a Nano board with built-in WiFi, I recommend the Nano 33 IoT:
https://store.arduino.cc/nano-33-iot

**Comment by enrutador** [comment]
Hi per1234 
A lot of thanks clarification ¡¡
