### ISSUE TITLE
Update documentation to include Arduino nano 33 IOT board

### ISSUE THREAD

**Issue by lorenzoromagnoli** [arduino-libraries/WiFiNINA#83]
It took me a good 20 minutes to figure out that I had to use this library to have the wifi of the nano 33 IOT working. 

I suggest updating the documentation of this library and make the gettig started guide [here](https://www.arduino.cc/en/Guide/NANO33IoT) more explicit.

**Comment by SimonePDA** [comment]
The getting started of the NANO 33 IoT references the WifiNINA library as we do in the other getting started. The reference was missing in the main library page and I added it there.
https://www.arduino.cc/en/Reference/Libraries
The description in the Lib Manager will include NANO 33 IoT in the WiFiNINA description.
