### ISSUE TITLE
UDP broadcasts stop working after a few packets

### ISSUE THREAD

**Issue by NameOfTheDragon** [arduino-libraries/WiFiNINA#88]
I have an application that sends a UDP broadcast every 10 seconds. Everything works fine for a few packets and then `endPacket()` starts returning false and no broadcast is sent.

I've spent ages trying all sorts of workarounds but the only thing that works is to drop the association and re-associate. Then the same thing, a few broadcasts will go out fine and then it stops working again.

Re-associating is a workaround of sorts but it causes a long delay and is not really a permanent solution.

This is (in essence) my sending code...

```cpp
// ...
WiFiUDP sender;
// ... 
sender.begin(0);
sender.clearWriteError();
sender.beginPacket(machine.broadcastAddress, Configuration::BroadcastPort);
serializeJson(json, sender);
sender.println();
auto sent = sender.endPacket();
```

**Comment by sandeepmistry** [comment]
Hi @NameOfTheDragon,

This is a known issue and reported in https://github.com/arduino-libraries/WiFiNINA/issues/77. I'll close this as a duplicate issue, please follow the one I linked above for any updates on this topic.
