### ISSUE TITLE
Minor fault in Example WiFiUdpSendReceiveString

### ISSUE THREAD

**Issue by dave-kitchen** [arduino-libraries/WiFiNINA#93]
packetBuffer is declared [255] but in line 83 a read request is made for (up to)255 bytes, in the following lines the returned length is used as an index - so could write to packetBuffer[255], one byte beyond the end.

**Comment by thekunalsaini** [comment]
We have to just increase the size of packetBuffer declared to [256] so that no error occur at line 83 in example

**Comment by thekunalsaini** [comment]
@per1234  we have increase buffer size.
what's your suggestion? Please mention

**Comment by Rocketct** [comment]
merged the PR i'll close the issue
