### ISSUE TITLE
Up date firmware on Nano IOT 33

### ISSUE THREAD

**Issue by Russell108** [arduino-libraries/WiFiNINA#96]
Unable to update firmware on Nano IOT 33, which will fix some bugs I have discussed elsewhere with the arduino team.

They suggested I could use third party tools to update but recommended I wait.
I have also been told the updater has been built to enable this but has yet to be posted in the main download of arduino so when can we expect this to appear.

Sorry if this is in the wrong place Its a wifi type issue so I posted here rather than the main arduino. Thanks

**Comment by Russell108** [comment]
anyone?

**Comment by sandeepmistry** [comment]
The following pull request in the IDE will provide NINA firmware v1.3.0: https://github.com/arduino/Arduino/pull/9552

Changelog for firmware changes can be found here: https://github.com/arduino/nina-fw/blob/master/CHANGELOG

**Comment by johnpneumann** [comment]
1.3.0 does not appear to be available for my Nano 33. The latest I see is 1.2.4 and 19.6.1.

**Comment by Russell108** [comment]
Ok I updated the library to 1.5 
I open WIFININA firmware updater I see the nano IOT 33 board 
I RUN THE firmware check
WiFiNINA firmware check.
22:33:49.910 -> 
22:33:50.691 -> Firmware version installed: 1.2.3
22:33:50.691 -> Latest firmware version available : 1.2.1
22:33:50.691 -> 
22:33:50.691 -> Check result: PASSED
how to update the firmware

**Comment by sandeepmistry** [comment]
You'll have to download the hourly Arduino build: https://www.arduino.cc/en/Main/Software#hourly

**Comment by Russell108** [comment]
I get error message 




If I click ok or don’t allow the message just re appears

**Comment by Russell108** [comment]
I don’t know if this is an issue

**Comment by Russell108** [comment]
I cannot open the hourly build referenced or the nightly build on OS X Catalina
the operating system  does not allow access to folders.
seems like the image  attached to the email didn't arrive so here they both are
![Screenshot 2020-01-07 at 22 41 29](https://user-images.githubusercontent.com/624111/71939465-a7f0d100-31aa-11ea-8aac-908a7c095878.png)
![Screenshot 2020-01-07 at 22 54 59](https://user-images.githubusercontent.com/624111/71939472-ae7f4880-31aa-11ea-8715-aa913888f852.png)
